### ISSUE TITLE
macOS Catalina

### ISSUE THREAD

**Issue by aram-manouk** [taboc741/MacScripts#4]
This doesn't work on macOS Catalina anymore. I have been trying to rewrite portions of the deferral script, but I haven't been able to figure it out.

**Comment by chadware-software** [comment]
aramig, I had to change the line

 if [ $remainDeferrals = ""]; then
to
if ! [ -n "$remainDeferrals" ]; then

Also changed the line updatesPending=`echo $updates | grep recommended`
to
updatesPending=`echo $updates | grep -i recommended`

This is now working for me

**Comment by taboc741** [comment]
Committed Chadman11's suggested edits to the the master.
